name = "cybersec-agent"
main = "src/index.js"
compatibility_date = "2024-01-01"
account_id = "82d842d586a0298981ab28617ec8ac66"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "CACHE"
id = "94f2859d6efd4fc8830887d5d797324a"

[vars]
MAX_TOKENS = "512"
TEMPERATURE = "0.3"

[[routes]]
pattern = "cybersec.mindhive.tech/*"
zone_id = "4f8b8a0bd742d7872f75b8144b3851f8"